# Generated by Django 4.1.3 on 2022-11-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='nickname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
