# Generated by Django 4.1.3 on 2022-11-21 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_address_house_number_alter_address_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.CreateModel(
            name='UserAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=20)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='addresses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.useraddresses'),
        ),
    ]
