# Generated by Django 4.1.3 on 2022-11-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_addresses_address_nickname_user_address_and_more'),
        ('users', '0006_user_address'),
    ]

    operations = [
    ]
