# Generated by Django 4.1.3 on 2022-11-26 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20221126_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='owner',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.user'),
            preserve_default=False,
        ),
    ]
